os:
  - linux
python:
  - "2.7"
  - "3.6"
  - "nightly" # currently points to 3.7-dev

dist: trusty
sudo: false
language: python


before_install:
  # Show build setup
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - python --version

addons:
  apt:
    packages:
    - graphviz
install:
  - pip install -r requirements.txt
  - if [ "v$TRAVIS_PYTHON_VERSION" == "v2.7" ];
    then
      pip install --upgrade mock;
    fi

script:
- export COVERAGE_FILE=/tmp/.coverage
- '(echo "[run]"; echo "branch = True"; echo "include = $(pwd)/ActionTree/*"; echo "concurrency = multiprocessing"; echo "[report]"; echo "exclude_lines ="; echo "  Not unittested: ...") > /tmp/.coveragerc'
- coverage run --rcfile=/tmp/.coveragerc setup.py test
- coverage combine
- if [ "v$TRAVIS_PYTHON_VERSION" == "v2.7" ];
  then
    python setup.py build_sphinx --builder=doctest;
  fi
script: 
  - python helpTest.py | grep ActionTree
  
after_success:
  - coveralls --rcfile=/tmp/.coveragerc
  - echo "OK, all done."

notifications:
  email:
    recipients:
      - ralic.lo.eng@ieee.org
    on_success: always # default: change
    on_failure: never # default: always

deploy:
- provider: pypi
  user: jacquev6
  password:
    secure: d3UoCrv3O53EeMhnhcfplSzc6R3aQqWES7d6gMwfeHlVib+k0GWKCMJqwKhrgMiqWxzW/DhK2t0fckwHgId2Fr6NyUZnIIto8X2wbQtbIIxV033y1DsVJgmEi2UjyJ5E7uI8+cnFLa8p7YgPXNt0cKajxHXSfBJY492nlQL1YRc=
  skip_upload_docs: true
  on:
    tags: true
    repo: jacquev6/ActionTree
    python: 2.7
- provider: pypi
  server: https://testpypi.python.org/pypi
  user: jacquev6
  password:
    secure: d3UoCrv3O53EeMhnhcfplSzc6R3aQqWES7d6gMwfeHlVib+k0GWKCMJqwKhrgMiqWxzW/DhK2t0fckwHgId2Fr6NyUZnIIto8X2wbQtbIIxV033y1DsVJgmEi2UjyJ5E7uI8+cnFLa8p7YgPXNt0cKajxHXSfBJY492nlQL1YRc=
  skip_upload_docs: true
  on:
    tags: false
    repo: jacquev6/ActionTree
    python: 2.7