language: python
python:
- 2.7
- 3.3
- 3.4
install:
- pip install sphinx coveralls
- if [ "v$TRAVIS_PYTHON_VERSION" == "v2.7" ]; then ln -s /usr/lib/python2.7/dist-packages/cairo ~/virtualenv/python2.7/lib/python2.7; fi
- if [ "v$TRAVIS_PYTHON_VERSION" == "v3.3" ]; then ln -s /usr/lib/python3/dist-packages/cairo ~/virtualenv/python3.3/lib/python3.3; fi
- if [ "v$TRAVIS_PYTHON_VERSION" == "v3.4" ]; then ln -s /usr/lib/python3/dist-packages/cairo ~/virtualenv/python3.4/lib/python3.4; fi
script:
- coverage run "--include=ActionTree/*" setup.py test
- if [ "v$TRAVIS_PYTHON_VERSION" == "v2.7" ]; then python setup.py build_sphinx --builder=doctest; fi
after_success:
- coveralls
deploy:
  provider: pypi
  user: jacquev6
  password:
    secure: d3UoCrv3O53EeMhnhcfplSzc6R3aQqWES7d6gMwfeHlVib+k0GWKCMJqwKhrgMiqWxzW/DhK2t0fckwHgId2Fr6NyUZnIIto8X2wbQtbIIxV033y1DsVJgmEi2UjyJ5E7uI8+cnFLa8p7YgPXNt0cKajxHXSfBJY492nlQL1YRc=
  on:
    tags: true
    repo: jacquev6/ActionTree
    python: 2.7
