language: python
python:
- "2.7"
- "3.5"
- "3.6"
sudo: false
addons:
  apt:
    packages:
    - graphviz
install:
- pip install --upgrade pip setuptools
- pip install --upgrade sphinx coveralls
- pip install --upgrade graphviz matplotlib wurlitzer
- if [ "v$TRAVIS_PYTHON_VERSION" == "v2.7" ];
  then
    pip install --upgrade mock;
  fi
script:
- coverage run setup.py test
- coverage combine
- if [ "v$TRAVIS_PYTHON_VERSION" == "v2.7" ];
  then
    python setup.py build_sphinx --builder=doctest;
  fi
after_success:
- coveralls
deploy:
- provider: pypi
  user: jacquev6
  password:
    secure: d3UoCrv3O53EeMhnhcfplSzc6R3aQqWES7d6gMwfeHlVib+k0GWKCMJqwKhrgMiqWxzW/DhK2t0fckwHgId2Fr6NyUZnIIto8X2wbQtbIIxV033y1DsVJgmEi2UjyJ5E7uI8+cnFLa8p7YgPXNt0cKajxHXSfBJY492nlQL1YRc=
  skip_upload_docs: true
  on:
    tags: true
    repo: jacquev6/ActionTree
    python: 2.7
- provider: pypi
  server: https://testpypi.python.org/pypi
  user: jacquev6
  password:
    secure: d3UoCrv3O53EeMhnhcfplSzc6R3aQqWES7d6gMwfeHlVib+k0GWKCMJqwKhrgMiqWxzW/DhK2t0fckwHgId2Fr6NyUZnIIto8X2wbQtbIIxV033y1DsVJgmEi2UjyJ5E7uI8+cnFLa8p7YgPXNt0cKajxHXSfBJY492nlQL1YRc=
  skip_upload_docs: true
  on:
    tags: false
    repo: jacquev6/ActionTree
    python: 2.7
