language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get install libcairo2-dev
  - if [ $(python -c "import sys; print(sys.version_info.major)") == 2 ]; then wget http://www.cairographics.org/releases/py2cairo-1.10.0.tar.bz2; fi
  - if [ $(python -c "import sys; print(sys.version_info.major)") == 3 ]; then wget http://www.cairographics.org/releases/pycairo-1.10.0.tar.bz2; fi
  - tar xf py*cairo-1.10.0.tar.bz2
  - cd py*cairo-1.10.0
  - ./waf configure --prefix=$(python -c "import sys; print(sys.prefix)")
  - ./waf build
  - ./waf install
  - cd ..
script:
  - python setup.py test
